main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix="/cliente")

app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request, redirect
from database.cliente import CLIENTES
from database.interface import ContaBancaria

cliente_route = Blueprint("cliente", __name__)

@cliente_route.route("/")
def lista_cliente():
    return render_template("lista_clientes.html", clientes=CLIENTES)

@cliente_route.route("/", methods=["POST"])
def consultar_cliente():
    cliente_consulta = ContaBancaria.consultarCPF(request.form.get("cpf"))
    if(cliente_consulta != None):
        return render_template("ver_cliente.html", cliente=cliente_consulta)
    else:
        cliente_consulta = {"nome": f'Cliente com o CPF: {request.form.get("cpf")} não existe.'}
        return render_template("cliente_inexistente.html", cliente=cliente_consulta)

@cliente_route.route("/criar", methods=["POST"])
def criar_cliente():
    ContaBancaria(request.form.get("nome"), request.form.get("cpf"))
    return redirect("/cliente", code=302)


@cliente_route.route("/criar")
def criar_form_cliente():
    return render_template("criar_form_cliente.html")

@cliente_route.route("/<int:cliente_id>")
def ver_cliente(cliente_id):
    cliente_consulta = None
    
    cliente_consulta = ContaBancaria.verCliente(cliente_id)
    if(cliente_consulta != None):
        return render_template("ver_cliente.html", cliente=cliente_consulta)
    else:
        cliente_consulta = {"nome": f"Cliente com o ID: {cliente_id} não existe."}
        return render_template("cliente_inexistente.html", cliente=cliente_consulta)

@cliente_route.route("/<int:cliente_id>/depositar", methods=["POST"])
def depositar_valor(cliente_id):
    for i in CLIENTES:
        if i['id'] == cliente_id:
            print(request.form.get("valor"))  
            ContaBancaria.depositar(cliente_id, request.form.get("valor"))
            return redirect(f"/cliente/{cliente_id}")

@cliente_route.route("/<int:cliente_id>/sacar", methods=["POST"])
def sacar_valor(cliente_id):
    for i in CLIENTES:
        if i['id'] == cliente_id:
            if(float(request.form.get("valor")) <= float(i['saldo_atual'])):
                ContaBancaria.sacar(cliente_id, request.form.get("valor"))
                return redirect(f"/cliente/{cliente_id}")
            else:
                return redirect(f"/cliente/{cliente_id}?saldo=false")
               
            

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint("home", __name__)

@home_route.route("/")
def home():
    return render_template("index.html")

templates/cliente_inexistente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Consultar Cliente</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>Falha ao procurar cliente</h1>
      <p>{{cliente.nome}}</p>
      <a
        type="button"
        href="{{url_for('cliente.lista_cliente')}}"
        class="btn btn-primary"
        >Voltar</a
      >
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/criar_form_cliente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Criar Cliente</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>Cadastro</h1>
      <form action="{{url_for('cliente.criar_cliente')}}" method="POST">
        <div class="mb-3">
          <label for="exampleInputCpf1" class="form-label"
            >Digite seu CPF</label
          >
          <input
            type="text"
            class="form-control"
            id="exampleInputCpf1"
            aria-describedby="cpf"
            name="cpf"
          />
        </div>
        <div class="mb-3">
          <label for="exampleInputNome1" class="form-label"
            >Digite seu Nome</label
          >
          <input
            type="text"
            class="form-control"
            id="exampleInputNome1"
            aria-describedby="nome"
            name="nome"
          />
        </div>
        <button type="submit" class="btn btn-primary">Criar Conta</button>
        <a href="{{url_for('home.home')}}" class="btn btn-secondary">Voltar</a>
      </form>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Lista de Clientes</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>Acesse sua conta</h1>
      <form action="{{url_for('cliente.consultar_cliente')}}" method="POST">
        <div class="mb-3">
          <label for="exampleInputCpf1" class="form-label"
            >Digite seu CPF</label
          >
          <input
            type="text"
            class="form-control"
            id="exampleInputCpf1"
            aria-describedby="cpf"
            name="cpf"
          />
        </div>
        <button type="submit" class="btn btn-success">Acessar Conta</button>
        <a
          href="{{url_for('cliente.criar_form_cliente')}}"
          class="btn btn-primary"
          >Criar Conta</a
        >
        <a href="{{url_for('cliente.lista_cliente')}}" class="btn btn-warning"
          >Lista de Clientes</a
        >
      </form>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/lista_clientes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Lista de Clientes</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <h1>Lista de Clientes</h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Nome</th>
            <th scope="col">CPF</th>
            <th scope="col">Saldo Atual</th>
            <th scope="col">Ação</th>
          </tr>
        </thead>
        <tbody>
          {% for cliente in clientes %}
          <tr>
            <th scope="row">{{cliente.id}}</th>
            <td>{{cliente.nome}}</td>
            <td>{{cliente.cpf}}</td>
            <td>R$ {{cliente.saldo_atual}}</td>
            <td>
              <a
                type="button"
                href="/cliente/{{cliente.id}}"
                class="btn btn-primary"
                >Acessar</a
              >
            </td>
          </tr>

          {% endfor %}
        </tbody>
      </table>
      <a href="{{url_for('cliente.criar_cliente')}}" class="btn btn-primary"
        >Criar Cliente</a
      >
      <a type="button" href="{{url_for('home.home')}}" class="btn btn-warning"
        >Acessar por CPF</a
      >
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/ver_cliente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Consultar Cliente</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/form.css" />
  </head>
  <body>
    <div class="container">
      <h1>Consultar Cliente</h1>
      <h4>Nome: {{cliente.nome}}</h4>
      <h4>CPF: {{cliente.cpf}}</h4>
      <h4>Saldo Atual: R${{cliente.saldo_atual}}</h4>

      <form
        method="post"
        action="{{url_for('cliente.sacar_valor', cliente_id=cliente.id)}}"
      >
        <div class="input-container">
          <input
            class="form-control"
            type="number"
            name="valor"
            placeholder="R$"
            type="text"
            step="0.01"
          />
          <button class="btn btn-primary" type="submit">Sacar</button>
        </div>
      </form>
      <form
        method="post"
        action="{{url_for('cliente.depositar_valor', cliente_id=cliente.id)}}"
      >
        <div class="input-container">
          <input
            class="form-control"
            type="number"
            name="valor"
            placeholder="R$"
            type="text"
            step="0.01"
          />
          <button class="btn btn-primary" type="submit">Depositar</button>
        </div>
      </form>
      <a
        type="button"
        href="{{url_for('cliente.lista_cliente')}}"
        class="btn btn-primary"
        >Voltar</a
      >
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script src="../static/ver_cliente.js"></script>
  </body>
</html>